### ISSUE TITLE
CSI

### ISSUE THREAD

**Issue by ana-oprescu** [linkyndy/software-testing#1]
You're assuming all liars are guilty.

**Comment by linkyndy** [comment]
Isn't it the other way around? I assume everybody not guilty to be honest, which is wrong.

**Comment by ana-oprescu** [comment]
He, I think both statements explain the why the following construction of "honest" is incorrect:

honest = boys \ guilty

First says you assume the third category of boys, liars, is a subset of the guilty category; therefore, the statement implies you assume boys are either guilty or honest.

Second says you assume boys are either guilty or honest.

**Comment by linkyndy** [comment]
Indeed. We've solved this in the variant we've submitted as a group. I forgot to modify mine as well :) Thanks!
